# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
jQuery ->
  $('.filterable .btn-filter').click ->
    $panel = $(this).parents('.filterable')
    $filters = $panel.find('.filters input')
    $tbody = $panel.find('.table tbody')
    if $filters.prop('disabled') == true
      $filters.prop 'disabled', false
      $filters.first().focus()
    else
      $filters.val('').prop 'disabled', true
      $tbody.find('.no-result').remove()
      $tbody.find('tr').show()
    return
  $('.filterable .filters input').keyup (e) ->
    code = e.keyCode or e.which
    if code == '9'
      return
    $input = $(this)
    inputContent = $input.val().toLowerCase()
    $panel = $input.parents('.filterable')
    column = $panel.find('.filters th').index($input.parents('th'))
    $table = $panel.find('.table')
    $rows = $table.find('tbody tr')
    $filteredRows = $rows.filter(->
      value = $(this).find('td').eq(column).text().toLowerCase()
      value.indexOf(inputContent) == -1
    )
    $table.find('tbody .no-result').remove()
    $rows.show()
    $filteredRows.hide()
    if $filteredRows.length == $rows.length
      $table.find('tbody').prepend $('<tr class="no-result text-center"><td colspan="' + $table.find('.filters th').length + '">No result found</td></tr>')
    return
  return

# ---
# generated by js2coffee 2.2.0